### ISSUE TITLE
Forecast

### ISSUE THREAD

**Issue by musdfakoc** [DarkKnight1991/Stock-Price-Prediction#4]
Hi thanks for the brilliant work. I want to know what should ı do for forecasting the future. I tried bunch of things yet I could not achieve it. Thanks already.

**Comment by vasilevskykv** [comment]
Hi! I would like to ask, does your Neural Network do predictions in real time?
I see, that one of your parameters in prediction is array of data. But when you need to predict future data, you don't have an array of data - you have only previous data and time interval for prediction and nothing more. 
As I undestand, you simply checked the prediction
